source 'https://rubygems.org'

require 'yaml'
config = YAML.load_file(File.expand_path('../../config.yml', __FILE__))

sage_git = if config['use_https_for_github']
             'https://github.com/Sage'
           else
             'git@github.com:Sage'
           end

sop_git = "#{sage_git}/sop"
bc_database_git = "#{sage_git}/bcdatabase"

gem 'rails', config['rails_version']
# Database gems
gem 'mysql2', '~> 0.4.10'
gem 'bcdatabase', git: bc_database_git, branch: '1.0.6-patched'

# SOP Engines
git sop_git, tag: config['sop_tag'] do
  gem 'sop'
  gem 'sop_mysageone'
  gem 'sop_bc'
  gem 'sop_dev', group: [:development, :test, :uat]
end

# Local engines
path '../' do
  gem 'global_taxation_api'
  gem 'global_taxation_commons'
end

# misc gems
gem 'rack-cache'
gem 'roadie'
gem 'roadie-rails'
gem 'jquery-rails'
gem 'dotiw'
gem 'nguyen'
gem 'daemons'
gem 'secure_headers', '3.9.0'
gem 'redcarpet', '>= 3.5.1'
gem 'activesupport'
gem 'acts_as_paranoid', '~> 0.5.0'
gem 'net-ssh'
gem 'fog-local'
gem 'fog', '1.38.0'
gem 'fog-core', '~> 1.32'
gem 'dogstatsd-ruby', '~> 1.6'
gem 'sprockets', '2.12.5'
gem 'soap4r-ng', '~> 2.0.3'
gem 'jwt'
gem 'redis-namespace'
gem 'ruby-saml'
gem 'i18n-js', '2.1.2'
gem 'sinject'
gem 'hash_kit'
gem 'aws-sdk', '<2.0'
gem 'aws-sdk-core', '2.6.0'
gem 'eventq_base', '~> 1.9.3'
gem 'eventq_rabbitmq', '~> 1.10.3'
gem 'eventq_aws', '~> 1.6.3', :source => 'https://rubygems.org/'
gem 'carrierwave', '1.3.2'
gem 'carrierwave_direct'
gem 'rack-protection', '~> 1.5.5'
gem 'rails-html-sanitizer', '~> 1.0.4'
gem 'rufus-scheduler'
gem 'omniauth', '~> 1.3.2'
gem 'kaminari', '>= 1.2.1'
gem 'excon', '>= 0.71.0'
gem 'rack', '>= 1.6.12'
gem 'user_agent_parser', '>= 2.6.0'
gem 'archive-zip', '~> 0.12.0'
gem 'sqlite3'
gem 'jmespath', '>= 1.6.1'

# Assets
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
#gem 'therubyracer'
gem 'tzinfo', '1.2.10'
gem 'tzinfo-data'
gem 'colorize'
gem 'actionview'

gem 'nokogiri', '>= 1.13.6'
gem 'loofah', '>= 2.3.1'
gem 'ffi', '~> 1.9.24'
gem 'rubyzip', '>= 1.3.0'
gem 'di'
gem 'middleware'
gem 'request_store'
gem 'factory_bot'

group :development, :test do
  gem 'thin'
  gem 'fudge'
  gem 'yard', '>= 0.9.20'
  gem 'flog'
  gem 'flay'
  gem 'brakeman', '~>3.4.1'
  gem 'ruby2ruby'
  gem 'diff-lcs', require: 'diff/lcs'
  gem 'simplecov'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'guard-rspec'
  gem 'letter_opener'
  gem 'rake', '>= 12.3.3'
  gem 'rspec', '>= 3.0.0'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-its'
  gem 'rspec-html-matchers'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers', '2.8.0'
  gem 'selenium-webdriver'
  gem 'roo'
  gem 'ruby-debug-ide'
  gem 'debase'
  gem 'rubocop', require: false
  gem 'rubocop-rails'

  if ENV['enablepry']
    gem 'pry'
    gem 'pry-byebug'
    gem 'pry-stack_explorer'
    gem 'binding_of_caller'
  end
end

group :uat do
  gem 'logput'
  gem 'newrelic_rpm', '~> 6.0.0.351'
end

group :preprod, :production, :sandbox do
  gem 'syslog-logger'
  gem 'newrelic_rpm', '~> 6.0.0.351'
end

group :development, :ci do
  gem 'puma', '4.3.12'
  gem 'passenger', '>= 5.3.2'
  gem 'rake', '>= 12.3.3'
end

# Any non default source should stay at bottom for security reasons
source 'https://sageonegems.jfrog.io/sageonegems/api/gems/gems' do
  gem 'proxy_authentication'
  gem 'sop_accountants', config['sop_accountants_version']
  gem 's1_logging'
end
